import {
    Box,
    Layers,
    Zap,
    LayoutGrid,
    Sparkles,
    Book,
    FileText,
    Shield,
    HelpCircle,
    Globe,
    User,
    Settings,
    ArrowRightLeft,
    Home,
    Twitter,
    Github,
    Send,
    Mail,
    ShoppingBag,
    Rocket,
    BarChart,
    Wallet,
    History,
    LifeBuoy,
    Code,
    Calendar,
    Edit,
    PlusCircle,
    LayoutTemplate
} from "lucide-react"

export const navigation = {
    main: [
        { title: "Home", href: "/", icon: Home, description: "Return to homepage" },
        { title: "Marketplace", href: "/marketplace", icon: ShoppingBag, description: "Trade IP assets" },
        { title: "Launchpad", href: "/launchpad", icon: Rocket, description: "Upcoming drops" },
        { title: "Portfolio", href: "/portfolio", icon: User, description: "View your IP portfolio" },
    ],
    marketplace: [
        { title: "All Assets", href: "/marketplace/assets", icon: Box, description: "Browse all IP assets" },
        { title: "Collections", href: "/marketplace/collections", icon: Layers, description: "View verified collections" },
        { title: "Activity", href: "/marketplace/activity", icon: BarChart, description: "Market trends and sales" },
    ],
    launchpad: [
        { title: "Creator Launchpad", href: "/launchpad", icon: Rocket, description: "Creator tools dashboard" },
        { title: "Collection Drop", href: "/launchpad/collection", icon: Layers, description: "Deploy a collection drop" },
        { title: "Mint Drop", href: "/launchpad/mint", icon: Zap, description: "Schedule a mint" },
        { title: "Create Collection", href: "/create/collection", icon: PlusCircle, description: "Start from scratch" },
        { title: "Create NFT", href: "/create/asset", icon: Box, description: "Mint single asset" },
        { title: "Create with IP Templates", href: "/create/template", icon: LayoutTemplate, description: "Use legal templates" },
        { title: "Create Remix", href: "/create/remix", icon: Sparkles, description: "Remix existing IP" },
        { title: "Claim Collection", href: "/claim/collection", icon: Shield, description: "Claim existing collection" },
        { title: "Claim Asset", href: "/claim/asset", icon: FileText, description: "Claim existing asset" },
    ],
    portfolio: [
        { title: "My Assets", href: "/portfolio/assets", icon: Box, description: "Your owned IP" },
        { title: "My Collections", href: "/portfolio/collections", icon: Layers, description: "Collections you created" },
        { title: "Wallet", href: "/portfolio/wallet", icon: Wallet, description: "Balance and settings" },
        { title: "History", href: "/portfolio/history", icon: History, description: "Transaction history" },
    ],
    discover: [
        { title: "IP Assets", href: "/assets", icon: Box, description: "Explore registered IP assets" },
        { title: "Collections", href: "/collections", icon: Layers, description: "Browse curated IP collections" },
        { title: "Activities", href: "/activities", icon: Zap, description: "Community events & rewards" },
    ],
    create: [
        { title: "Mint Asset", href: "/create/asset", icon: Box, description: "Register new IP on-chain" },
        { title: "New Collection", href: "/create/collection", icon: Layers, description: "Launch a verifiable collection" },
        { title: "Remix", href: "/create/remix", icon: Sparkles, description: "Create derivative works" },
    ],
    resources: [
        { title: "Documentation", href: "/docs", icon: FileText, description: "Technical guides & API refs" },
        { title: "Governance", href: "/docs/mediolano-dao", icon: Shield, description: "DAO voting & proposals" },
        { title: "Help Center", href: "/docs/faq", icon: HelpCircle, description: "FAQs and support" },
        { title: "Developers", href: "/docs/developers", icon: Code, description: "SDKs and tools" },
        { title: "Status", href: "/status", icon: LifeBuoy, description: "System status" },
    ],
    socials: [
        { title: "X (Twitter)", href: "https://x.com/MediolanoApp", icon: Twitter },
        { title: "GitHub", href: "https://github.com/mediolano-app", icon: Github },
        { title: "Telegram", href: "https://t.me/integrityweb", icon: Send },
        { title: "Email", href: "mailto:medialanexyz@gmail.com", icon: Mail },
    ]
}
